### PR TITLE
Try testing scripts copying files & using non-master branch for plugin

### PR DESCRIPTION
**Pull request by DrJukka**

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Removing "io.jxcore.node"
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "62743a32e279d39d71c7cceae7bc2a8134d3c4fa".
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Removing "io.jxcore.node"
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "62743a32e279d39d71c7cceae7bc2a8134d3c4fa".
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Removing "io.jxcore.node"
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "62743a32e279d39d71c7cceae7bc2a8134d3c4fa".
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Removing "io.jxcore.node"
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "62743a32e279d39d71c7cceae7bc2a8134d3c4fa".
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Removing "io.jxcore.node"
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "62743a32e279d39d71c7cceae7bc2a8134d3c4fa".
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Removing "io.jxcore.node"
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "62743a32e279d39d71c7cceae7bc2a8134d3c4fa".
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task

**Comment by yaronyg** [comment]
This are the experiments to actually get the CLI working. The good news is that when our install works the CLI environment works. But we still have problems with install.

**Comment by ThaliTester** [comment]
Test 47908698 has failed

See https://gist.github.com/1aac11f020a5c0014802 for the fail logs

**Pull request closed without merging**
