### PR TITLE
Updating build script and json config

### PR DESCRIPTION
**Pull request by yaronyg**
This is now set up to run the perf tests, I hope.

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: Could not find the application path. Check build location on mobile_test.json


[0;31mcompilation aborted
 [0m
[0;31mcompilation aborted
 [0m


Could not find the application path. Check build location on mobile_test.json

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: scp: /Users/thali/Github/testBuild//tmp/ThaliBuild/Thali_CordovaPlugin/test/TestServer: No such file or directory


[0;31mcompilation aborted
 [0m


scp: /Users/thali/Github/testBuild//tmp/ThaliBuild/Thali_CordovaPlugin/test/TestServer: No such file or directory

```

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/27f6d2c7ac04ee17dfbb for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/ba9273f478da6e7c3c14 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/7207c9a78e5d72c66755 for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/3cc0bd1b5c635f275905 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/2be60a33b788c16e20d1 for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/e2866026e71f1e4e07fd for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/ea649757980c61dc0e21 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/cd8b3d92e948040a364e for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/ca5ad849aaccc8b14758 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/d261d53bad0f61eaa7cb for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/088a63a8a8cad13b8c2b for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/baa186299620e8f52196 for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/2200cf5fd6a00785fb70 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47970403 build process is completed

See https://gist.github.com/45289cac1cfe1596d05a for the logs

**Comment by ThaliTester** [comment]
Test 47970403 has failed

See https://gist.github.com/41c72c4eb0039f0b85d7 for the fail logs

**Comment by yaronyg** [comment]
This isn't needed anymore since we moved testing to Thali_CordovaPlugin

**Pull request closed without merging**
