### PR TITLE
Reproduce network reliability issues in the CI.

### PR DESCRIPTION
**Pull request by vjrantal**

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (176a311)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (176a311)

See https://github.com/ThaliTester/TestResults/tree/49526184176a311_Build_only_Android__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184176a311(176a311) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/49526184176a311_Build_only_Android__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (ca93672)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (ca93672)

See https://github.com/ThaliTester/TestResults/tree/49526184ca93672_Build_only_Android__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184ca93672(ca93672) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184ca93672_Build_only_Android__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cc21a54)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (cc21a54)

See https://github.com/ThaliTester/TestResults/tree/49526184cc21a54_Build_only_Android__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184cc21a54(cc21a54) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184cc21a54_Build_only_Android__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (791338a)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (791338a)

See https://github.com/ThaliTester/TestResults/tree/49526184791338a_Build_only_Android__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184791338a(791338a) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184791338a_Build_only_Android__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1e19499)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (1e19499)

See https://github.com/ThaliTester/TestResults/tree/495261841e19499_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 495261841e19499(1e19499) has failed

See https://github.com/ThaliTester/TestResults/tree/495261841e19499_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (d88d809)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (d88d809)

See https://github.com/ThaliTester/TestResults/tree/49526184d88d809_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184d88d809(d88d809) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184d88d809_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (feb5d05)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (feb5d05)

See https://github.com/ThaliTester/TestResults/tree/49526184feb5d05_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184feb5d05(feb5d05) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184feb5d05_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cc21a54)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (8b51d14)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (5edbe03)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (cc21a54)

See https://github.com/ThaliTester/TestResults/tree/49526184cc21a54_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184cc21a54(cc21a54) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184cc21a54_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (8b51d14)

See https://github.com/ThaliTester/TestResults/tree/495261848b51d14_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 495261848b51d14(8b51d14) has failed

See https://github.com/ThaliTester/TestResults/tree/495261848b51d14_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (5edbe03)

See https://github.com/ThaliTester/TestResults/tree/495261845edbe03_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 495261845edbe03(5edbe03) has failed

See https://github.com/ThaliTester/TestResults/tree/495261845edbe03_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (f10be1e)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (f10be1e)

See https://github.com/ThaliTester/TestResults/tree/49526184f10be1e_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (fb75016)

**Comment by ThaliTester** [comment]
Test 49526184f10be1e(f10be1e) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184f10be1e_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (fb75016)

See https://github.com/ThaliTester/TestResults/tree/49526184fb75016_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (f698367)

**Comment by ThaliTester** [comment]
Test 49526184fb75016(fb75016) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184fb75016_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (f698367)

See https://github.com/ThaliTester/TestResults/tree/49526184f698367_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184f698367(f698367) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184f698367_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (cd4fb85)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (6d7bbdf)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (a3a5cb3)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (cd4fb85)

See https://github.com/ThaliTester/TestResults/tree/49526184cd4fb85_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184cd4fb85(cd4fb85) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/49526184cd4fb85_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (6d7bbdf)

See https://github.com/ThaliTester/TestResults/tree/495261846d7bbdf_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 495261846d7bbdf(6d7bbdf) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/495261846d7bbdf_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (a3a5cb3)

See https://github.com/ThaliTester/TestResults/tree/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184a3a5cb3(a3a5cb3) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a3a5cb3)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (a3a5cb3)

See https://github.com/ThaliTester/TestResults/tree/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184a3a5cb3(a3a5cb3) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (a3a5cb3)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (a3a5cb3)

See https://github.com/ThaliTester/TestResults/tree/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184a3a5cb3(a3a5cb3) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184a3a5cb3_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by yaronyg** [comment]
Oguz wants to try a few extra things to see if he can figure it out.

**Comment by yaronyg** [comment]
This is the PR for #7

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (b4f3aa9)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (b4f3aa9)

See https://github.com/ThaliTester/TestResults/tree/49526184b4f3aa9_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184b4f3aa9(b4f3aa9) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184b4f3aa9_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4451736)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (4451736)

See https://github.com/ThaliTester/TestResults/tree/495261844451736_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 495261844451736(4451736) has failed

See https://github.com/ThaliTester/TestResults/tree/495261844451736_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (549c368)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (549c368)

See https://github.com/ThaliTester/TestResults/tree/49526184549c368_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184549c368(549c368) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184549c368_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (1f420de)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (1f420de)

See https://github.com/ThaliTester/TestResults/tree/495261841f420de_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 495261841f420de(1f420de) has failed

See https://github.com/ThaliTester/TestResults/tree/495261841f420de_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (480b105)

**Comment by ThaliTester** [comment]
Test (Success) 49526184 build is completed (480b105)

See https://github.com/ThaliTester/TestResults/tree/49526184480b105_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the logs

**Comment by ThaliTester** [comment]
Test 49526184480b105(480b105) has failed

See https://github.com/ThaliTester/TestResults/tree/49526184480b105_Reproduce_network_reliability_issues_in_the_CI__vjrantal/ for the fail logs

**Pull request closed without merging**
