### PR TITLE
Yet another test

### PR DESCRIPTION
**Pull request by mattpodwysocki**
More testing

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47666685 has successfully finished without an error

See https://gist.github.com/60a80c4200393328dd3a for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test Server build has failed. See error details below; 
```Error: Command failed: android-sdk version check failed ("/Users/thali/Github/testBuild/platforms/android/cordova/android_sdk_version"), continuing anyways.
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/thali/Github/testBuild/www/jxcore/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "install" "--loglevel" "http" "--color" "true" "--autoremove=*.gz" "--save" "--build-from-source"
npm ERR! cwd /Users/thali/Github/testBuild/www/jxcore
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path /Users/thali/Github/testBuild/www/jxcore/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/testBuild/www/jxcore/npm-debug.log
npm ERR! not ok code 0
Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)


Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.example.hello
	Name: HelloWorld
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android
Installing "io.jxcore.node" for android
Fetching plugin "https://github.com/thaliproject/Thali_CordovaPlugin" via git clone
Repository "https://github.com/thaliproject/Thali_CordovaPlugin" checked out to git ref "master".
Installing "org.thaliproject.p2p" for android
-e [0;31mcompilation aborted
 [0m
compilation aborted
 [0m


android-sdk version check failed ("/Users/thali/Github/testBuild/platforms/android/cordova/android_sdk_version"), continuing anyways.
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/thali/Github/testBuild/www/jxcore/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.5.0
npm ERR! command "/usr/local/bin/jx" "/Users/thali/.jx/npm" "install" "--loglevel" "http" "--color" "true" "--autoremove=*.gz" "--save" "--build-from-source"
npm ERR! cwd /Users/thali/Github/testBuild/www/jxcore
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.14
npm ERR! path /Users/thali/Github/testBuild/www/jxcore/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/thali/Github/testBuild/www/jxcore/npm-debug.log
npm ERR! not ok code 0
Error: Cannot find module 'fs-extra-promise'
    at Function.Module._oldRes (module.js:774:9)
    at Function.Module._resolveFilename (module.js:1606:15)
    at Function.Module._load (module.js:335:17)
    at Module.require (module.js:451:15)
    at require (module.js:469:13)
    at Object.<anonymous> (/Users/thali/Github/testBuild/plugins/org.thaliproject.p2p/scripts/androidAfterPrepare.js:3:10)
    at Module._compile (module.js:595:24)
    at Object.Module._extensions..js (module.js:625:8)
    at Module.load (module.js:416:30)
    at Function.Module._load (module.js:380:8)

```

**Comment by yaronyg** [comment]
@mattpodwysocki can we close this?

**Pull request closed without merging**
