### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by obastemur**

### CODE REVIEW

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://gist.github.com/4e91d1408aa6e3da7e51 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 has successfully finished without an error

See https://gist.github.com/9724518a0ed98e26a2b3 for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://gist.github.com/21f8882d28a2dc1a3051 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 has successfully finished without an error

See https://gist.github.com/6856c6d3438ba09abe92 for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 has successfully finished without an error

See https://gist.github.com/7d5f12408a6d6607fbfa for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed

See https://gist.github.com/e8a491bd01424377c15c for the fail logs

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://gist.github.com/834fbfba4f310ab07bf9 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed

See https://gist.github.com/586c5e7941a1786dc15a for the logs

**Comment by ThaliTester** [comment]
Test 47672234 has successfully finished without an error

See https://gist.github.com/3272d93e5dfdc5f28cf5 for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed

See https://gist.github.com/28c07f020baa181378c4 for the logs

**Comment by ThaliTester** [comment]
Test 47672234 has successfully finished without an error

See https://gist.github.com/038dd82dbc5b81e0de03 for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 4. task

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed

See https://gist.github.com/40c482c3415ced60bec6 for the logs

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://gist.github.com/e96e8c6b23b0aba3e6d0 for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file. 

error: pathspec '47672234_Update_build.sh_obastemur_34' did not match any file(s) known to git.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file. 

error: pathspec '47672234_Update_build_sh_obastemur_34' did not match any file(s) known to git.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file. 

error: pathspec '47672234_Update_build_sh_obastemur_34' did not match any file(s) known to git.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file. 

error: pathspec '47672234_Update_build_sh_obastemur_34' did not match any file(s) known to git.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file.

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file.

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://github.com/ThaliTester/TestResults/tree/47672234_Update_build_sh_obastemur_99999/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. Commit Index:undefined

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. Commit Index:28

**Comment by ThaliTester** [comment]
Build is completed without an error but couldn't commint the log file.

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://github.com/ThaliTester/TestResults/tree/47672234_Update_build_sh_obastemur_99999/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. Commit Index:fe314f4

**Comment by obastemur** [comment]
test #fe314f4

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed

See https://github.com/ThaliTester/TestResults/tree/47672234_Update_build_sh_obastemur_fe314f4/ for the logs

**Comment by ThaliTester** [comment]
Test 47672234 has failed

See https://github.com/ThaliTester/TestResults/tree/47672234_Update_build_sh_obastemur_fe314f4/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. Commit Index:ea88e58

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed (ea88e58)

See https://github.com/ThaliTester/TestResults/tree/47672234ea88e58_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 47672234ea88e58 has failed

See https://github.com/ThaliTester/TestResults/tree/47672234ea88e58_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. Commit Index:dd78cb7

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed (dd78cb7)

See https://github.com/ThaliTester/TestResults/tree/47672234dd78cb7_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 47672234dd78cb7(dd78cb7) has failed

See https://github.com/ThaliTester/TestResults/tree/47672234dd78cb7_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (1143541)

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed (1143541)

See https://github.com/ThaliTester/TestResults/tree/476722341143541_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 476722341143541(1143541) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/476722341143541_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (56c0496)

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed (56c0496)

See https://github.com/ThaliTester/TestResults/tree/4767223456c0496_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 4767223456c0496(56c0496) has failed

See https://github.com/ThaliTester/TestResults/tree/4767223456c0496_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (e263d5f)

**Comment by ThaliTester** [comment]
Test 47672234 build process is completed (e263d5f)

See https://github.com/ThaliTester/TestResults/tree/47672234e263d5f_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 47672234e263d5f(e263d5f) has successfully finished without an error

See https://github.com/ThaliTester/TestResults/tree/47672234e263d5f_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (041ec31)

**Comment by ThaliTester** [comment]
Test (Success) 47672234 build is completed (041ec31)

See https://github.com/ThaliTester/TestResults/tree/47672234041ec31_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 47672234041ec31(041ec31) has failed

See https://github.com/ThaliTester/TestResults/tree/47672234041ec31_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7fc8662)

**Comment by ThaliTester** [comment]
Test (Success) 47672234 build is completed (7fc8662)

See https://github.com/ThaliTester/TestResults/tree/476722347fc8662_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 476722347fc8662(7fc8662) has failed

See https://github.com/ThaliTester/TestResults/tree/476722347fc8662_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7fc8662)

**Comment by ThaliTester** [comment]
Test (Success) 47672234 build is completed (7fc8662)

See https://github.com/ThaliTester/TestResults/tree/476722347fc8662_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 476722347fc8662(7fc8662) has failed

See https://github.com/ThaliTester/TestResults/tree/476722347fc8662_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (7fc8662)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 2. task. (b686059)

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 3. task. (907c1b8)

**Comment by ThaliTester** [comment]
Test (Success) 47672234 build is completed (7fc8662)

See https://github.com/ThaliTester/TestResults/tree/476722347fc8662_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 476722347fc8662(7fc8662) has failed

See https://github.com/ThaliTester/TestResults/tree/476722347fc8662_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
Test (Success) 47672234 build is completed (b686059)

See https://github.com/ThaliTester/TestResults/tree/47672234b686059_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test (Success) 47672234 build is completed (907c1b8)

See https://github.com/ThaliTester/TestResults/tree/47672234907c1b8_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
Test 47672234907c1b8(907c1b8) has failed

See https://github.com/ThaliTester/TestResults/tree/47672234907c1b8_Update_build_sh_obastemur/ for the fail logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4b8b505)

**Comment by ThaliTester** [comment]
Test (Fail) 47672234 build is completed (4b8b505)

See https://github.com/ThaliTester/TestResults/tree/476722344b8b505_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (3060164)

**Comment by ThaliTester** [comment]
Test (Fail) 47672234 build is completed (3060164)

See https://github.com/ThaliTester/TestResults/tree/476722343060164_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (bcd88f4)

**Comment by ThaliTester** [comment]
Test (Fail) 47672234 build is completed (bcd88f4)

See https://github.com/ThaliTester/TestResults/tree/47672234bcd88f4_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (5948119)

**Comment by ThaliTester** [comment]
Test (Fail) 47672234 build is completed (5948119)

See https://github.com/ThaliTester/TestResults/tree/476722345948119_Update_build_sh_obastemur/ for the logs

**Comment by ThaliTester** [comment]
PR is added to the queue for testing as 1. task. (4a1fb91)

**Comment by ThaliTester** [comment]
Test (Fail) 47672234 build is completed (4a1fb91)

See https://github.com/ThaliTester/TestResults/tree/476722344a1fb91_Update_build_sh_obastemur/ for the logs

**Pull request closed without merging**
